param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "E:\BaiduNetdiskDownload\S32K144 AUTOSAR工具包\share_20230823\AUTOSAR_TOOLs\IAR_v8.40.2\common\bin\cspybat" -f "E:\BaiduNetdiskDownload\SIP-S32K14x\AUTOSAR_TOOLs\S32K144_SIP\MICROSAR\CBD1800257_D01_S32K1xx\Applications\S32K144_Start_new_IAR\settings\ASR_S32K144_Start.Debug.general.xcl" --backend -f "E:\BaiduNetdiskDownload\SIP-S32K14x\AUTOSAR_TOOLs\S32K144_SIP\MICROSAR\CBD1800257_D01_S32K1xx\Applications\S32K144_Start_new_IAR\settings\ASR_S32K144_Start.Debug.driver.xcl" 
}
else
{
& "E:\BaiduNetdiskDownload\S32K144 AUTOSAR工具包\share_20230823\AUTOSAR_TOOLs\IAR_v8.40.2\common\bin\cspybat" -f "E:\BaiduNetdiskDownload\SIP-S32K14x\AUTOSAR_TOOLs\S32K144_SIP\MICROSAR\CBD1800257_D01_S32K1xx\Applications\S32K144_Start_new_IAR\settings\ASR_S32K144_Start.Debug.general.xcl" --debug_file=$debugfile --backend -f "E:\BaiduNetdiskDownload\SIP-S32K14x\AUTOSAR_TOOLs\S32K144_SIP\MICROSAR\CBD1800257_D01_S32K1xx\Applications\S32K144_Start_new_IAR\settings\ASR_S32K144_Start.Debug.driver.xcl" 
}
