/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *          File:  Rte_Hook.h
 *        Config:  S32K144_Start.dpa
 *   ECU-Project:  MyECU
 *
 *     Generator:  MICROSAR RTE Generator Version 4.19.0
 *                 RTE Core Version 1.19.0
 *       License:  CBD1800257
 *
 *   Description:  Header file containing definitions for VFB tracing
 *********************************************************************************************************************/


/**********************************************************************************************************************
 * Names of available VFB-Trace-Hooks
 **********************************************************************************************************************
 *
 * Not configured:
 *
 *  Rte_CallHook_CtLedTask_UR_CN_CAN00_06ecbb07_GetCurrentComMode_Return
 *  Rte_CallHook_CtLedTask_UR_CN_CAN00_06ecbb07_GetCurrentComMode_Start
 *  Rte_CallHook_CtLedTask_UR_CN_CAN00_06ecbb07_GetMaxComMode_Return
 *  Rte_CallHook_CtLedTask_UR_CN_CAN00_06ecbb07_GetMaxComMode_Start
 *  Rte_CallHook_CtLedTask_UR_CN_CAN00_06ecbb07_GetRequestedComMode_Return
 *  Rte_CallHook_CtLedTask_UR_CN_CAN00_06ecbb07_GetRequestedComMode_Start
 *  Rte_CallHook_CtLedTask_UR_CN_CAN00_06ecbb07_RequestComMode_Return
 *  Rte_CallHook_CtLedTask_UR_CN_CAN00_06ecbb07_RequestComMode_Start
 *  Rte_CallHook_Dcm_DataServices_Diag_RWDI_LightOnOffCounter_LightOnOffCounter_Value_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Diag_RWDI_LightOnOffCounter_LightOnOffCounter_Value_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Diag_RWDI_LightOnOffCounter_LightOnOffCounter_Value_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Diag_RWDI_LightOnOffCounter_LightOnOffCounter_Value_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Diag_RWDI_LightOnOffCounter_LightOnOffCounter_Value_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Diag_RWDI_LightOnOffCounter_LightOnOffCounter_Value_WriteData_Start
 *  Rte_CallHook_Dcm_SecurityAccess_Level_01_CompareKey_Return
 *  Rte_CallHook_Dcm_SecurityAccess_Level_01_CompareKey_Start
 *  Rte_CallHook_Dcm_SecurityAccess_Level_01_GetSeed_Return
 *  Rte_CallHook_Dcm_SecurityAccess_Level_01_GetSeed_Start
 *  Rte_CallHook_DemMaster_0_CBReadData_OccurrenceCounter_OccurenceCounter_ReadData_Return
 *  Rte_CallHook_DemMaster_0_CBReadData_OccurrenceCounter_OccurenceCounter_ReadData_Start
 *  Rte_CallHook_DemMaster_0_CBReadData_OdometerValue_OdometerValue_ReadData_Return
 *  Rte_CallHook_DemMaster_0_CBReadData_OdometerValue_OdometerValue_ReadData_Start
 *  Rte_CallHook_DemSatellite_0_CBReadData_OccurrenceCounter_OccurenceCounter_ReadData_Return
 *  Rte_CallHook_DemSatellite_0_CBReadData_OccurrenceCounter_OccurenceCounter_ReadData_Start
 *  Rte_CallHook_DemSatellite_0_CBReadData_OdometerValue_OdometerValue_ReadData_Return
 *  Rte_CallHook_DemSatellite_0_CBReadData_OdometerValue_OdometerValue_ReadData_Start
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_0_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_0_requestedMode_Start
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_1_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_1_requestedMode_Start
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_0_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_0_requestedMode_Start
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_1_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_1_requestedMode_Start
 *  Rte_Runnable_BswM_BswM_MainFunction_Return
 *  Rte_Runnable_BswM_BswM_MainFunction_Start
 *  Rte_Runnable_CddSbc_Sbc_Test_Runnable_Return
 *  Rte_Runnable_CddSbc_Sbc_Test_Runnable_Start
 *  Rte_Runnable_ComM_ComM_MainFunction_0_Return
 *  Rte_Runnable_ComM_ComM_MainFunction_0_Start
 *  Rte_Runnable_ComM_GetCurrentComMode_Return
 *  Rte_Runnable_ComM_GetCurrentComMode_Start
 *  Rte_Runnable_ComM_GetInhibitionStatus_Return
 *  Rte_Runnable_ComM_GetInhibitionStatus_Start
 *  Rte_Runnable_ComM_GetMaxComMode_Return
 *  Rte_Runnable_ComM_GetMaxComMode_Start
 *  Rte_Runnable_ComM_GetRequestedComMode_Return
 *  Rte_Runnable_ComM_GetRequestedComMode_Start
 *  Rte_Runnable_ComM_LimitChannelToNoComMode_Return
 *  Rte_Runnable_ComM_LimitChannelToNoComMode_Start
 *  Rte_Runnable_ComM_LimitECUToNoComMode_Return
 *  Rte_Runnable_ComM_LimitECUToNoComMode_Start
 *  Rte_Runnable_ComM_PreventWakeUp_Return
 *  Rte_Runnable_ComM_PreventWakeUp_Start
 *  Rte_Runnable_ComM_ReadInhibitCounter_Return
 *  Rte_Runnable_ComM_ReadInhibitCounter_Start
 *  Rte_Runnable_ComM_RequestComMode_Return
 *  Rte_Runnable_ComM_RequestComMode_Start
 *  Rte_Runnable_ComM_ResetInhibitCounter_Return
 *  Rte_Runnable_ComM_ResetInhibitCounter_Start
 *  Rte_Runnable_ComM_SetECUGroupClassification_Return
 *  Rte_Runnable_ComM_SetECUGroupClassification_Start
 *  Rte_Runnable_CtLedTask_CtLedTask_InitRunnable_Return
 *  Rte_Runnable_CtLedTask_CtLedTask_InitRunnable_Start
 *  Rte_Runnable_CtLedTask_LedRunnable_Return
 *  Rte_Runnable_CtLedTask_LedRunnable_Start
 *  Rte_Runnable_Dcm_Dcm_MainFunction_Return
 *  Rte_Runnable_Dcm_Dcm_MainFunction_Start
 *  Rte_Runnable_Dcm_GetActiveProtocol_Return
 *  Rte_Runnable_Dcm_GetActiveProtocol_Start
 *  Rte_Runnable_Dcm_GetRequestKind_Return
 *  Rte_Runnable_Dcm_GetRequestKind_Start
 *  Rte_Runnable_Dcm_GetSecurityLevel_Return
 *  Rte_Runnable_Dcm_GetSecurityLevel_Start
 *  Rte_Runnable_Dcm_GetSesCtrlType_Return
 *  Rte_Runnable_Dcm_GetSesCtrlType_Start
 *  Rte_Runnable_Dcm_ResetToDefaultSession_Return
 *  Rte_Runnable_Dcm_ResetToDefaultSession_Start
 *  Rte_Runnable_Dcm_SetActiveDiagnostic_Return
 *  Rte_Runnable_Dcm_SetActiveDiagnostic_Start
 *  Rte_Runnable_DemMaster_0_ClearDTC_Return
 *  Rte_Runnable_DemMaster_0_ClearDTC_Start
 *  Rte_Runnable_DemMaster_0_Dem_MasterMainFunction_Return
 *  Rte_Runnable_DemMaster_0_Dem_MasterMainFunction_Start
 *  Rte_Runnable_DemMaster_0_GetDTCOfEvent_Return
 *  Rte_Runnable_DemMaster_0_GetDTCOfEvent_Start
 *  Rte_Runnable_DemMaster_0_GetDTCStatusAvailabilityMask_Return
 *  Rte_Runnable_DemMaster_0_GetDTCStatusAvailabilityMask_Start
 *  Rte_Runnable_DemMaster_0_GetDebouncingOfEvent_Return
 *  Rte_Runnable_DemMaster_0_GetDebouncingOfEvent_Start
 *  Rte_Runnable_DemMaster_0_GetEventEnableCondition_Return
 *  Rte_Runnable_DemMaster_0_GetEventEnableCondition_Start
 *  Rte_Runnable_DemMaster_0_GetEventExtendedDataRecordEx_Return
 *  Rte_Runnable_DemMaster_0_GetEventExtendedDataRecordEx_Start
 *  Rte_Runnable_DemMaster_0_GetEventFailed_Return
 *  Rte_Runnable_DemMaster_0_GetEventFailed_Start
 *  Rte_Runnable_DemMaster_0_GetEventFreezeFrameDataEx_Return
 *  Rte_Runnable_DemMaster_0_GetEventFreezeFrameDataEx_Start
 *  Rte_Runnable_DemMaster_0_GetEventMemoryOverflow_Return
 *  Rte_Runnable_DemMaster_0_GetEventMemoryOverflow_Start
 *  Rte_Runnable_DemMaster_0_GetEventStatus_Return
 *  Rte_Runnable_DemMaster_0_GetEventStatus_Start
 *  Rte_Runnable_DemMaster_0_GetEventTested_Return
 *  Rte_Runnable_DemMaster_0_GetEventTested_Start
 *  Rte_Runnable_DemMaster_0_GetEventUdsStatus_Return
 *  Rte_Runnable_DemMaster_0_GetEventUdsStatus_Start
 *  Rte_Runnable_DemMaster_0_GetFaultDetectionCounter_Return
 *  Rte_Runnable_DemMaster_0_GetFaultDetectionCounter_Start
 *  Rte_Runnable_DemMaster_0_GetMonitorStatus_Return
 *  Rte_Runnable_DemMaster_0_GetMonitorStatus_Start
 *  Rte_Runnable_DemMaster_0_GetNumberOfEventMemoryEntries_Return
 *  Rte_Runnable_DemMaster_0_GetNumberOfEventMemoryEntries_Start
 *  Rte_Runnable_DemMaster_0_GetOperationCycleState_Return
 *  Rte_Runnable_DemMaster_0_GetOperationCycleState_Start
 *  Rte_Runnable_DemMaster_0_PostRunRequested_Return
 *  Rte_Runnable_DemMaster_0_PostRunRequested_Start
 *  Rte_Runnable_DemMaster_0_SelectDTC_Return
 *  Rte_Runnable_DemMaster_0_SelectDTC_Start
 *  Rte_Runnable_DemMaster_0_SetOperationCycleState_Return
 *  Rte_Runnable_DemMaster_0_SetOperationCycleState_Start
 *  Rte_Runnable_DemSatellite_0_Dem_SatelliteMainFunction_Return
 *  Rte_Runnable_DemSatellite_0_Dem_SatelliteMainFunction_Start
 *  Rte_Runnable_DemSatellite_0_GetDTCOfEvent_Return
 *  Rte_Runnable_DemSatellite_0_GetDTCOfEvent_Start
 *  Rte_Runnable_DemSatellite_0_GetDebouncingOfEvent_Return
 *  Rte_Runnable_DemSatellite_0_GetDebouncingOfEvent_Start
 *  Rte_Runnable_DemSatellite_0_GetEventEnableCondition_Return
 *  Rte_Runnable_DemSatellite_0_GetEventEnableCondition_Start
 *  Rte_Runnable_DemSatellite_0_GetEventExtendedDataRecordEx_Return
 *  Rte_Runnable_DemSatellite_0_GetEventExtendedDataRecordEx_Start
 *  Rte_Runnable_DemSatellite_0_GetEventFailed_Return
 *  Rte_Runnable_DemSatellite_0_GetEventFailed_Start
 *  Rte_Runnable_DemSatellite_0_GetEventFreezeFrameDataEx_Return
 *  Rte_Runnable_DemSatellite_0_GetEventFreezeFrameDataEx_Start
 *  Rte_Runnable_DemSatellite_0_GetEventStatus_Return
 *  Rte_Runnable_DemSatellite_0_GetEventStatus_Start
 *  Rte_Runnable_DemSatellite_0_GetEventTested_Return
 *  Rte_Runnable_DemSatellite_0_GetEventTested_Start
 *  Rte_Runnable_DemSatellite_0_GetEventUdsStatus_Return
 *  Rte_Runnable_DemSatellite_0_GetEventUdsStatus_Start
 *  Rte_Runnable_DemSatellite_0_GetFaultDetectionCounter_Return
 *  Rte_Runnable_DemSatellite_0_GetFaultDetectionCounter_Start
 *  Rte_Runnable_DemSatellite_0_GetMonitorStatus_Return
 *  Rte_Runnable_DemSatellite_0_GetMonitorStatus_Start
 *  Rte_Runnable_DemSatellite_0_ResetEventDebounceStatus_Return
 *  Rte_Runnable_DemSatellite_0_ResetEventDebounceStatus_Start
 *  Rte_Runnable_DemSatellite_0_ResetEventStatus_Return
 *  Rte_Runnable_DemSatellite_0_ResetEventStatus_Start
 *  Rte_Runnable_DemSatellite_0_SetEventStatus_Return
 *  Rte_Runnable_DemSatellite_0_SetEventStatus_Start
 *  Rte_Runnable_Det_ReportError_Return
 *  Rte_Runnable_Det_ReportError_Start
 *  Rte_Runnable_Det_ReportRuntimeError_Return
 *  Rte_Runnable_Det_ReportRuntimeError_Start
 *  Rte_Runnable_EcuM_EcuM_MainFunction_Return
 *  Rte_Runnable_EcuM_EcuM_MainFunction_Start
 *  Rte_Runnable_EcuM_GetBootTarget_Return
 *  Rte_Runnable_EcuM_GetBootTarget_Start
 *  Rte_Runnable_EcuM_GetLastShutdownTarget_Return
 *  Rte_Runnable_EcuM_GetLastShutdownTarget_Start
 *  Rte_Runnable_EcuM_GetShutdownCause_Return
 *  Rte_Runnable_EcuM_GetShutdownCause_Start
 *  Rte_Runnable_EcuM_GetShutdownTarget_Return
 *  Rte_Runnable_EcuM_GetShutdownTarget_Start
 *  Rte_Runnable_EcuM_SelectBootTarget_Return
 *  Rte_Runnable_EcuM_SelectBootTarget_Start
 *  Rte_Runnable_EcuM_SelectShutdownCause_Return
 *  Rte_Runnable_EcuM_SelectShutdownCause_Start
 *  Rte_Runnable_EcuM_SelectShutdownTarget_Return
 *  Rte_Runnable_EcuM_SelectShutdownTarget_Start
 *  Rte_Runnable_Os_OsCore0_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore0_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore0_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore0_swc_GetElapsedValue_Start
 *  Rte_SwitchAckHook_Dcm_DcmEcuReset_DcmEcuReset_Return
 *  Rte_SwitchAckHook_Dcm_DcmEcuReset_DcmEcuReset_Start
 *  Rte_SwitchHook_BswM_Switch_ESH_ModeSwitch_BswM_MDGP_ESH_Mode_Return
 *  Rte_SwitchHook_BswM_Switch_ESH_ModeSwitch_BswM_MDGP_ESH_Mode_Start
 *  Rte_SwitchHook_Dcm_DcmControlDtcSetting_DcmControlDtcSetting_Return
 *  Rte_SwitchHook_Dcm_DcmControlDtcSetting_DcmControlDtcSetting_Start
 *  Rte_SwitchHook_Dcm_DcmDiagnosticSessionControl_DcmDiagnosticSessionControl_Return
 *  Rte_SwitchHook_Dcm_DcmDiagnosticSessionControl_DcmDiagnosticSessionControl_Start
 *  Rte_SwitchHook_Dcm_DcmEcuReset_DcmEcuReset_Return
 *  Rte_SwitchHook_Dcm_DcmEcuReset_DcmEcuReset_Start
 *  Rte_Task_Activate
 *  Rte_Task_Dispatch
 *  Rte_Task_WaitEvent
 *  Rte_Task_WaitEventRet
 *  SchM_EnterHook_BswM_BSWM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_BswM_BSWM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_BOTH_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_BOTH_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_RX_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_RX_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_TX_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_TX_Start
 *  SchM_EnterHook_Dcm_DCM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Dcm_DCM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_Det_DET_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Det_DET_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_00_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_00_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_01_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_01_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_02_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_02_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_03_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_03_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_04_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_04_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_05_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_05_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_06_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_06_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_07_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_07_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_08_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_08_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_09_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_09_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_10_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_10_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_11_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_11_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_12_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_12_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_13_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_13_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_14_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_14_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_15_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_15_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_16_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_16_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_17_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_17_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_18_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_18_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_19_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_19_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_20_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_20_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_21_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_21_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_22_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_22_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_23_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_23_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_24_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_24_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_25_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_25_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_26_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_26_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_27_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_27_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_28_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_28_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_29_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_29_Start
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_30_Return
 *  SchM_EnterHook_Dio_DIO_EXCLUSIVE_AREA_30_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_00_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_00_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_01_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_01_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_02_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_02_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_03_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_03_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_04_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_04_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_05_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_05_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_06_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_06_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_07_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_07_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_08_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_08_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_09_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_09_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_10_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_10_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_11_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_11_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_12_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_12_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_13_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_13_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_14_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_14_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_15_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_15_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_16_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_16_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_17_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_17_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_18_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_18_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_19_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_19_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_20_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_20_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_21_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_21_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_22_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_22_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_23_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_23_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_24_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_24_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_25_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_25_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_26_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_26_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_27_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_27_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_28_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_28_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_29_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_29_Start
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_30_Return
 *  SchM_EnterHook_Mcu_MCU_EXCLUSIVE_AREA_30_Start
 *  SchM_EnterHook_PduR_PDUR_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_PduR_PDUR_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_00_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_00_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_01_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_01_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_02_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_02_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_03_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_03_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_04_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_04_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_05_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_05_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_06_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_06_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_07_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_07_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_08_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_08_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_09_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_09_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_10_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_10_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_11_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_11_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_12_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_12_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_13_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_13_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_14_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_14_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_15_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_15_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_16_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_16_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_17_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_17_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_18_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_18_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_19_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_19_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_20_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_20_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_21_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_21_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_22_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_22_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_23_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_23_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_24_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_24_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_25_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_25_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_26_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_26_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_27_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_27_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_28_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_28_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_29_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_29_Start
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_30_Return
 *  SchM_EnterHook_Port_PORT_EXCLUSIVE_AREA_30_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_00_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_00_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_01_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_01_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_02_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_02_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_03_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_03_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_04_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_04_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_05_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_05_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_06_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_06_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_07_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_07_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_08_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_08_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_09_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_09_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_10_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_10_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_11_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_11_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_12_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_12_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_13_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_13_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_14_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_14_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_15_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_15_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_16_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_16_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_17_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_17_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_18_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_18_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_19_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_19_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_20_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_20_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_21_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_21_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_22_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_22_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_23_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_23_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_24_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_24_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_25_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_25_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_26_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_26_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_27_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_27_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_28_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_28_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_29_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_29_Start
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_30_Return
 *  SchM_EnterHook_Spi_SPI_EXCLUSIVE_AREA_30_Start
 *  SchM_ExitHook_BswM_BSWM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_BswM_BSWM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_BOTH_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_BOTH_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_RX_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_RX_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_TX_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_TX_Start
 *  SchM_ExitHook_Dcm_DCM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Dcm_DCM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_Det_DET_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Det_DET_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_00_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_00_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_01_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_01_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_02_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_02_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_03_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_03_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_04_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_04_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_05_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_05_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_06_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_06_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_07_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_07_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_08_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_08_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_09_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_09_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_10_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_10_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_11_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_11_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_12_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_12_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_13_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_13_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_14_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_14_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_15_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_15_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_16_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_16_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_17_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_17_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_18_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_18_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_19_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_19_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_20_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_20_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_21_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_21_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_22_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_22_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_23_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_23_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_24_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_24_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_25_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_25_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_26_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_26_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_27_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_27_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_28_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_28_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_29_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_29_Start
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_30_Return
 *  SchM_ExitHook_Dio_DIO_EXCLUSIVE_AREA_30_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_00_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_00_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_01_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_01_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_02_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_02_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_03_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_03_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_04_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_04_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_05_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_05_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_06_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_06_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_07_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_07_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_08_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_08_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_09_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_09_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_10_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_10_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_11_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_11_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_12_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_12_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_13_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_13_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_14_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_14_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_15_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_15_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_16_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_16_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_17_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_17_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_18_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_18_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_19_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_19_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_20_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_20_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_21_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_21_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_22_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_22_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_23_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_23_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_24_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_24_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_25_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_25_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_26_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_26_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_27_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_27_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_28_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_28_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_29_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_29_Start
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_30_Return
 *  SchM_ExitHook_Mcu_MCU_EXCLUSIVE_AREA_30_Start
 *  SchM_ExitHook_PduR_PDUR_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_PduR_PDUR_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_00_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_00_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_01_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_01_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_02_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_02_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_03_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_03_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_04_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_04_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_05_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_05_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_06_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_06_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_07_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_07_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_08_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_08_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_09_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_09_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_10_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_10_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_11_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_11_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_12_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_12_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_13_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_13_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_14_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_14_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_15_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_15_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_16_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_16_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_17_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_17_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_18_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_18_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_19_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_19_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_20_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_20_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_21_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_21_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_22_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_22_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_23_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_23_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_24_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_24_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_25_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_25_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_26_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_26_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_27_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_27_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_28_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_28_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_29_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_29_Start
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_30_Return
 *  SchM_ExitHook_Port_PORT_EXCLUSIVE_AREA_30_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_00_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_00_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_01_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_01_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_02_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_02_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_03_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_03_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_04_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_04_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_05_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_05_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_06_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_06_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_07_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_07_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_08_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_08_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_09_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_09_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_10_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_10_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_11_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_11_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_12_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_12_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_13_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_13_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_14_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_14_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_15_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_15_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_16_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_16_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_17_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_17_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_18_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_18_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_19_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_19_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_20_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_20_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_21_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_21_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_22_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_22_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_23_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_23_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_24_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_24_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_25_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_25_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_26_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_26_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_27_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_27_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_28_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_28_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_29_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_29_Start
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_30_Return
 *  SchM_ExitHook_Spi_SPI_EXCLUSIVE_AREA_30_Start
 *  SchM_Schedulable_BswM_BswM_MainFunction_Return
 *  SchM_Schedulable_BswM_BswM_MainFunction_Start
 *  SchM_Schedulable_CanSM_CanSM_MainFunction_Return
 *  SchM_Schedulable_CanSM_CanSM_MainFunction_Start
 *  SchM_Schedulable_CanTp_CanTp_MainFunction_Return
 *  SchM_Schedulable_CanTp_CanTp_MainFunction_Start
 *  SchM_Schedulable_Can_Can_MainFunction_BusOff_Return
 *  SchM_Schedulable_Can_Can_MainFunction_BusOff_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Mode_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Mode_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Wakeup_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Wakeup_Start
 *  SchM_Schedulable_ComM_ComM_MainFunction_0_Return
 *  SchM_Schedulable_ComM_ComM_MainFunction_0_Start
 *  SchM_Schedulable_Com_Com_MainFunctionRx_Return
 *  SchM_Schedulable_Com_Com_MainFunctionRx_Start
 *  SchM_Schedulable_Com_Com_MainFunctionTx_Return
 *  SchM_Schedulable_Com_Com_MainFunctionTx_Start
 *  SchM_Schedulable_Dcm_Dcm_MainFunction_Return
 *  SchM_Schedulable_Dcm_Dcm_MainFunction_Start
 *  SchM_Schedulable_Dem_Dem_MasterMainFunction_Return
 *  SchM_Schedulable_Dem_Dem_MasterMainFunction_Start
 *  SchM_Schedulable_Dem_Dem_SatelliteMainFunction_Return
 *  SchM_Schedulable_Dem_Dem_SatelliteMainFunction_Start
 *  SchM_Schedulable_EcuM_EcuM_MainFunction_Return
 *  SchM_Schedulable_EcuM_EcuM_MainFunction_Start
 *  SchM_Schedulable_Spi_Spi_MainFunction_Handling_Return
 *  SchM_Schedulable_Spi_Spi_MainFunction_Handling_Start
 *
 *********************************************************************************************************************/

/* double include prevention */
#ifndef _RTE_HOOK_H
# define _RTE_HOOK_H

# include "Os.h" /* PRQA S 0828, 0883 */ /* MD_MSR_1.1_828, MD_Rte_Os */

# include "Rte_Type.h"
# include "Rte_Cfg.h"

# ifndef RTE_VFB_TRACE
#  define RTE_VFB_TRACE (0)
# endif

#endif /* _RTE_HOOK_H */

/**********************************************************************************************************************
 MISRA 2004 violations and justifications
 *********************************************************************************************************************/

/* module specific MISRA deviations:
   MD_Rte_Os:
     Reason:     This justification is used as summary justification for all deviations caused by the MICROSAR OS
                 which is for testing of the RTE. Those deviations are no issues in the RTE code.
     Risk:       No functional risk.
     Prevention: Not required.

*/
